//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMIDEX_WCF_Client.WCFRenaultService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportsDTO", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.Shared.DTO")]
    [System.SerializableAttribute()]
    public partial class ReportsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateExpertiseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImmatriculationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commercialPicturesLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string damagePicturesLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detailedLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificationPicturesLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string simplifiedLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateExpertise {
            get {
                return this.DateExpertiseField;
            }
            set {
                if ((this.DateExpertiseField.Equals(value) != true)) {
                    this.DateExpertiseField = value;
                    this.RaisePropertyChanged("DateExpertise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Immatriculation {
            get {
                return this.ImmatriculationField;
            }
            set {
                if ((object.ReferenceEquals(this.ImmatriculationField, value) != true)) {
                    this.ImmatriculationField = value;
                    this.RaisePropertyChanged("Immatriculation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commercialPicturesLink {
            get {
                return this.commercialPicturesLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.commercialPicturesLinkField, value) != true)) {
                    this.commercialPicturesLinkField = value;
                    this.RaisePropertyChanged("commercialPicturesLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string damagePicturesLink {
            get {
                return this.damagePicturesLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.damagePicturesLinkField, value) != true)) {
                    this.damagePicturesLinkField = value;
                    this.RaisePropertyChanged("damagePicturesLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detailedLink {
            get {
                return this.detailedLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.detailedLinkField, value) != true)) {
                    this.detailedLinkField = value;
                    this.RaisePropertyChanged("detailedLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificationPicturesLink {
            get {
                return this.identificationPicturesLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.identificationPicturesLinkField, value) != true)) {
                    this.identificationPicturesLinkField = value;
                    this.RaisePropertyChanged("identificationPicturesLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string simplifiedLink {
            get {
                return this.simplifiedLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.simplifiedLinkField, value) != true)) {
                    this.simplifiedLinkField = value;
                    this.RaisePropertyChanged("simplifiedLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgusPrixDTO", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.DTO.Argus")]
    [System.SerializableAttribute()]
    public partial class ArgusPrixDTO : DAMIDEX_WCF_Client.WCFRenaultService.Base {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnneeModeleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrixNeufHTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrixNeufTTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegmentLibelleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneeModele {
            get {
                return this.AnneeModeleField;
            }
            set {
                if ((object.ReferenceEquals(this.AnneeModeleField, value) != true)) {
                    this.AnneeModeleField = value;
                    this.RaisePropertyChanged("AnneeModele");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrixNeufHT {
            get {
                return this.PrixNeufHTField;
            }
            set {
                if ((object.ReferenceEquals(this.PrixNeufHTField, value) != true)) {
                    this.PrixNeufHTField = value;
                    this.RaisePropertyChanged("PrixNeufHT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrixNeufTTC {
            get {
                return this.PrixNeufTTCField;
            }
            set {
                if ((object.ReferenceEquals(this.PrixNeufTTCField, value) != true)) {
                    this.PrixNeufTTCField = value;
                    this.RaisePropertyChanged("PrixNeufTTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegmentLibelle {
            get {
                return this.SegmentLibelleField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentLibelleField, value) != true)) {
                    this.SegmentLibelleField = value;
                    this.RaisePropertyChanged("SegmentLibelle");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Base", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.DTO.Argus")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DAMIDEX_WCF_Client.WCFRenaultService.ArgusPrixDTO))]
    public partial class Base : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnneeProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneeProduction {
            get {
                return this.AnneeProductionField;
            }
            set {
                if ((object.ReferenceEquals(this.AnneeProductionField, value) != true)) {
                    this.AnneeProductionField = value;
                    this.RaisePropertyChanged("AnneeProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculeInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.Shared.DTO")]
    [System.SerializableAttribute()]
    public partial class VehiculeInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdIdexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdIdex {
            get {
                return this.IdIdexField;
            }
            set {
                if ((object.ReferenceEquals(this.IdIdexField, value) != true)) {
                    this.IdIdexField = value;
                    this.RaisePropertyChanged("IdIdex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDTO", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.Shared.DTO")]
    [System.SerializableAttribute()]
    public partial class VehicleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommercialNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfCirculationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DAMIDEX_WCF_Client.WCFRenaultService.Energies EnergyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsSentToClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotificationLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatingPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommercialName {
            get {
                return this.CommercialNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommercialNameField, value) != true)) {
                    this.CommercialNameField = value;
                    this.RaisePropertyChanged("CommercialName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfCirculation {
            get {
                return this.DateOfCirculationField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfCirculationField, value) != true)) {
                    this.DateOfCirculationField = value;
                    this.RaisePropertyChanged("DateOfCirculation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DAMIDEX_WCF_Client.WCFRenaultService.Energies Energy {
            get {
                return this.EnergyField;
            }
            set {
                if ((this.EnergyField.Equals(value) != true)) {
                    this.EnergyField = value;
                    this.RaisePropertyChanged("Energy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSite {
            get {
                return this.IdSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSiteField, value) != true)) {
                    this.IdSiteField = value;
                    this.RaisePropertyChanged("IdSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSentToClient {
            get {
                return this.IsSentToClientField;
            }
            set {
                if ((this.IsSentToClientField.Equals(value) != true)) {
                    this.IsSentToClientField = value;
                    this.RaisePropertyChanged("IsSentToClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationLink {
            get {
                return this.NotificationLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.NotificationLinkField, value) != true)) {
                    this.NotificationLinkField = value;
                    this.RaisePropertyChanged("NotificationLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPVO {
            get {
                return this.NumPVOField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPVOField, value) != true)) {
                    this.NumPVOField = value;
                    this.RaisePropertyChanged("NumPVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatingPlaces {
            get {
                return this.SeatingPlacesField;
            }
            set {
                if ((this.SeatingPlacesField.Equals(value) != true)) {
                    this.SeatingPlacesField = value;
                    this.RaisePropertyChanged("SeatingPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Energies", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.Shared")]
    public enum Energies : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ES = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EL = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HY = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/DAMIDEX.Server")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFRenaultService.IRenaultService")]
    public interface IRenaultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/GenerrerRapportExpertise", ReplyAction="http://tempuri.org/IRenaultService/GenerrerRapportExpertiseResponse")]
        DAMIDEX_WCF_Client.WCFRenaultService.ReportsDTO[] GenerrerRapportExpertise(string immatricule, System.Nullable<System.DateTime> dateExpertise, string vin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/GenerrerRapportExpertise", ReplyAction="http://tempuri.org/IRenaultService/GenerrerRapportExpertiseResponse")]
        System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.ReportsDTO[]> GenerrerRapportExpertiseAsync(string immatricule, System.Nullable<System.DateTime> dateExpertise, string vin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/LoadPricesFor", ReplyAction="http://tempuri.org/IRenaultService/LoadPricesForResponse")]
        DAMIDEX_WCF_Client.WCFRenaultService.ArgusPrixDTO[] LoadPricesFor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/LoadPricesFor", ReplyAction="http://tempuri.org/IRenaultService/LoadPricesForResponse")]
        System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.ArgusPrixDTO[]> LoadPricesForAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/LoadInterventionByClient", ReplyAction="http://tempuri.org/IRenaultService/LoadInterventionByClientResponse")]
        DAMIDEX_WCF_Client.WCFRenaultService.VehiculeInfoDTO[] LoadInterventionByClient(int IdClient, bool IsExported);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/LoadInterventionByClient", ReplyAction="http://tempuri.org/IRenaultService/LoadInterventionByClientResponse")]
        System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.VehiculeInfoDTO[]> LoadInterventionByClientAsync(int IdClient, bool IsExported);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/CreateInspection", ReplyAction="http://tempuri.org/IRenaultService/CreateInspectionResponse")]
        DAMIDEX_WCF_Client.WCFRenaultService.Response CreateInspection(DAMIDEX_WCF_Client.WCFRenaultService.VehicleDTO vehicles, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenaultService/CreateInspection", ReplyAction="http://tempuri.org/IRenaultService/CreateInspectionResponse")]
        System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.Response> CreateInspectionAsync(DAMIDEX_WCF_Client.WCFRenaultService.VehicleDTO vehicles, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRenaultServiceChannel : DAMIDEX_WCF_Client.WCFRenaultService.IRenaultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RenaultServiceClient : System.ServiceModel.ClientBase<DAMIDEX_WCF_Client.WCFRenaultService.IRenaultService>, DAMIDEX_WCF_Client.WCFRenaultService.IRenaultService {
        
        public RenaultServiceClient() {
        }
        
        public RenaultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RenaultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RenaultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RenaultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DAMIDEX_WCF_Client.WCFRenaultService.ReportsDTO[] GenerrerRapportExpertise(string immatricule, System.Nullable<System.DateTime> dateExpertise, string vin, string token) {
            return base.Channel.GenerrerRapportExpertise(immatricule, dateExpertise, vin, token);
        }
        
        public System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.ReportsDTO[]> GenerrerRapportExpertiseAsync(string immatricule, System.Nullable<System.DateTime> dateExpertise, string vin, string token) {
            return base.Channel.GenerrerRapportExpertiseAsync(immatricule, dateExpertise, vin, token);
        }
        
        public DAMIDEX_WCF_Client.WCFRenaultService.ArgusPrixDTO[] LoadPricesFor(int id) {
            return base.Channel.LoadPricesFor(id);
        }
        
        public System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.ArgusPrixDTO[]> LoadPricesForAsync(int id) {
            return base.Channel.LoadPricesForAsync(id);
        }
        
        public DAMIDEX_WCF_Client.WCFRenaultService.VehiculeInfoDTO[] LoadInterventionByClient(int IdClient, bool IsExported) {
            return base.Channel.LoadInterventionByClient(IdClient, IsExported);
        }
        
        public System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.VehiculeInfoDTO[]> LoadInterventionByClientAsync(int IdClient, bool IsExported) {
            return base.Channel.LoadInterventionByClientAsync(IdClient, IsExported);
        }
        
        public DAMIDEX_WCF_Client.WCFRenaultService.Response CreateInspection(DAMIDEX_WCF_Client.WCFRenaultService.VehicleDTO vehicles, string token) {
            return base.Channel.CreateInspection(vehicles, token);
        }
        
        public System.Threading.Tasks.Task<DAMIDEX_WCF_Client.WCFRenaultService.Response> CreateInspectionAsync(DAMIDEX_WCF_Client.WCFRenaultService.VehicleDTO vehicles, string token) {
            return base.Channel.CreateInspectionAsync(vehicles, token);
        }
    }
}
